# Generated by Django 2.0.8 on 2018-09-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TxHash', models.CharField(max_length=100)),
                ('timeStamp', models.DateTimeField()),
                ('from_addr', models.CharField(max_length=42)),
                ('to_addr', models.CharField(max_length=42)),
                ('value', models.FloatField()),
                ('gasUsedByTxn', models.FloatField()),
            ],
        ),
    ]
